---
title: "The road not taken"
author: jeannyz
date: 2020-05-11
email: jeanny@microsoft.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
 This is one of the most favourite poems that I like. It's about the inevitable choice in life.
 We all have to make various kinds of choices such as whether to work to continue to study.
 Hope it'll be helpful for your experience.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
---
